### ISSUE TITLE
Should not attempt to process __init__.py files

### ISSUE THREAD

**Issue by sebbASF** [Humbedooh/ahapi#3]
https://github.com/Humbedooh/ahapi/blob/661b9ab14250a85f20d43cf67be32561e9dc68d1/ahapi/server.py#L68

**Comment by sebbASF** [comment]
There may be a good reason to allow other scripts starting __, so the check should be for the exact name only.

**Comment by Humbedooh** [comment]
This was fixed in c65cb60
